name: myTunes Digital Distribution
favicon: null
layout_spectrum: 1
typography_spectrum: 0.29024744569323957
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b2b2b2'
    - '#272727'
    - '#f4f4f4'
    - '#006c9a'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
